apiVersion: v1
kind: Pod
metadata:
  name: firefox-pod
  labels:
    app: firefoxApplication
spec:
  containers:
    - name: firfox-container
      image: linuxserver/firefox
      ports:
        - containerPort: 3000