apiVersion: v1
kind: Pod
metadata:
  name: todoui-frontend
  labels:
    app: firefoxApplication
spec:
  containers:
    - name: firfox-container
      image: practice30.azurecr.io/todoui:v14
      ports:
        - containerPort: 80